dist: trusty
sudo: false
language: java
services:
  - docker
if: tag IS blank
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - ./gradlew clean build -PbuildNumber="$TRAVIS_BUILD_NUMBER"
  - ./gradlew dockerPush -PbuildNumber="$TRAVIS_BUILD_NUMBER"
  - ./gradlew dockerPushlatest -PbuildNumber="$TRAVIS_BUILD_NUMBER"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git tag $TRAVIS_BUILD_NUMBER
  - git push -q https://${GH_TOKEN}@github.com/robisrob/kafka_experiment --tags  2> /dev/null